import type { OrbState } from './types';

export const STATE_LABELS: Record<OrbState, string> = {
  working: 'Working…',
  searching: 'Searching…',
  solving: 'Solving…',
  listening: 'Listening…',
  connecting: 'Connecting…',
  weaving: 'Weaving…',
  composing: 'Composing…',
  breathing: 'Thinking…',
  shaping: 'Shaping…',
  idle: 'Idle',
  thinking: 'Thinking…',
  analyzing: 'Analysing…',
  booking: 'Booking…',
  streaming: 'Streaming…',
  success: 'Done',
  tracing: 'Tracing…',
  waiting: 'Waiting…',
  reasoning: 'Reasoning…',
  queuing: 'Queued…',
  reading: 'Reading…',
  gathering: 'Gathering…',
  syncing: 'Syncing…',
  comparing: 'Comparing…',
  drafting: 'Drafting…',
  retrying: 'Retrying…',
  error: 'Something went wrong',
  committing: 'Confirming…',
  progressing: 'In progress…',
  monitoring: 'Monitoring…',
  diverting: 'Finding an alternative…',
  verifying: 'Verifying…',
  activating: 'Activating…',
  plotting: 'Plotting…',
  focusing: 'Focusing…',
  pondering: 'Pondering…',
  recalling: 'Recalling…',
  cubing: 'Cubing…',
  building: 'Building…',
  hypercube: 'Folding…',
  conjuring: 'Conjuring…',
  conjuring_static: 'Holding…',
  assembling: 'Assembling…',
  evolving: 'Evolving…',
  spinning: 'Syncing…',
  responding: 'Responding…',
  presence: 'Here',
  cognition: 'Thinking…',
  speaking: 'Speaking…',
  relaying: 'Relaying…'
};
